### ISSUE TITLE
For Gradle 7 compatibility configuration of Distribution should switch to `setDistributionBaseName`

### ISSUE THREAD

**Issue by simonbasle** [reyerizo/jcstress-gradle-plugin#32]
Reporting this because for now we're getting deprecation warnings while building with the latest Gradle 6.7, so it is not an _immediate_ concern ;)

See https://docs.gradle.org/6.7/dsl/org.gradle.api.distribution.Distribution.html#org.gradle.api.distribution.Distribution:baseName

The deprecated API usage is at https://github.com/jerzykrlk/jcstress-gradle-plugin/blob/003f33739d907cae9e5574ad2fb291f66855efd8/src/main/java/com/github/erizo/gradle/JcstressPlugin.java#L296

**Comment by jerzykrlk** [comment]
Hi Simon, thanks for reporting that. I noticed that `distributionBaseName` isn't available in Gradle 5.4.1, so I think I'll keep the `baseName` for now. 

Would you be able to recommend an approach to keep the plugin compatible with 5.x?

**Comment by simonbasle** [comment]
Nope I don't think that will be possible. Given the Gradle release cadence, we can _maybe_ expect version 7 to be released in November or December (about 1 year after 6.0 and/or six weeks after 6.7 which was just released) 🤔

**Comment by carl-mastrangelo** [comment]
Since 7.0 is out now, would it be possible to see if there is a work around for both 5 and 7?

**Comment by jerzykrlk** [comment]
Hi Carl, 

I've implemented a workaround here: https://github.com/reyerizo/jcstress-gradle-plugin/pull/35

I'm not very happy with the code I wrote - any feedback would be appreciated. 

If nothing comes in till Friday, I'll just merge the change as is, and release a new version.

**Comment by carl-mastrangelo** [comment]
> I'm not very happy with the code I wrote - any feedback would be appreciated.

Such is the life of library maintainers ... I'm not very familiar with Gradle's APIs, but the code read easy enough and having those tests is great.   I think having something that works is better than something beautiful.   

The main reason I was interested in this is that Gradle 7.0 supports JDK 16.   I found out after filing this issue that Gradle 6.9 is getting JDK 16 support backported, so it's not as urgent that the jcstress plugin works with it.  Don't feel pressured into getting that PR out if you want to hold off, as my main goal has a work around for now.

**Comment by jerzykrlk** [comment]
Ok, thanks for the review! 
I've added a small test case and I'll try (can't promise) to release the new version tomorrow.

**Comment by jerzykrlk** [comment]
Okay - released.
